export enum RoomEvents {
    CreateRoom = 'createRoom',
    JoinRoom = 'joinRoom',
    LockRoom = 'lockRoom',
    UnlockRoom = 'unlockRoom',
    ShareCharacter = 'shareCharacter',
    RemovePlayer = 'removePlayer',
    DisconnectPlayer = 'disconnectPlayer',
    GetRoom = 'getRoom',
    RoomCreated = 'roomCreated',
    JoinError = 'joinError',
    LockError = 'lockError',
    UnlockError = 'unlockError',
    CharacterError = 'characterError',
    RemoveError = 'removeError',
    DisconnectError = 'disconnectError',
    RoomError = 'roomError',
    RoomData = 'roomData',
    PlayerJoined = 'playerJoined',
    PlayerRemoved = 'playerRemoved',
    PlayerDisconnected = 'playerDisconnected',
    RoomLocked = 'roomLocked',
    RoomUnlocked = 'roomUnlocked',
    Welcome = 'welcome',
}