import { Cell } from '@common/board';
import { Visibility } from '@common/enums';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { ApiProperty } from '@nestjs/swagger';
import { Document, Types } from 'mongoose';

export type BoardDocument = Board & Document;

@Schema({ timestamps: true })
export class Board {
    @ApiProperty({ description: 'Unique id generated by mongoDB' })
    @Prop({ type: String, default: () => new Types.ObjectId().toString(), auto: true })
    _id?: string;

    @ApiProperty({ description: 'Unique name for the board' })
    @Prop({ required: true, unique: true })
    name: string;

    @ApiProperty({ description: 'Board description' })
    @Prop()
    description: string;

    @ApiProperty({ description: 'Number representing the size of a single board column', examples: ['10', '15', '20'] })
    @Prop({ required: true })
    size: number;

    @ApiProperty({ description: 'Is the board made for the CTF game mode' })
    @Prop({ required: true, default: false })
    isCTF: boolean;

    @ApiProperty({ description: 'Board state' })
    @Prop({ type: [[Object]], required: true })
    board: Cell[][];

    @ApiProperty({ description: 'Whether the board is available to everyone' })
    @Prop({ required: true, enum: ['Public', 'Private'] })
    visibility: Visibility;

    @ApiProperty({ description: 'Date when the board was last modified' })
    @Prop({ required: true })
    updatedAt: Date;

    @ApiProperty({ description: 'Date when the board was created' })
    @Prop({ required: true })
    createdAt: Date;
}

export const boardSchema = SchemaFactory.createForClass(Board);
